SELECT * FROM CP_ORDER;
SELECT * FROM CP_ORDER_COURSE;
SELECT * FROM CP_COURSE;
SELECT * FROM CP_SECTION;
SELECT * FROM CP_LECTURE;
SELECT * FROM CP_QUIZ;
SELECT * FROM CP_QUIZ_QUESTION;
SELECT * FROM CP_NOTE;
SELECT * FROM CP_CATEGORY;
SELECT * FROM CP_USER;
SELECT * FROM CP_USER_DETAIL;
SELECT * FROM CP_PROFILE;
SELECT * FROM CP_USER_PROFILE;
SELECT * FROM CP_WISHLIST;
SELECT * FROM CP_ENROLLMENT;
SELECT * FROM CP_CART_ITEM;
SELECT * FROM CP_SHOPPING_SESSION;
SELECT * FROM CP_DISCOUNT;
SELECT * FROM CP_PAYMENT;
SELECT * FROM CP_REFUND;
SELECT * FROM CP_REVIEW;
SELECT * FROM CP_PROFILE_IMAGE;
SELECT * FROM CP_COURSE_IMAGE;
SELECT * FROM CP_LECTURE_VIDEO;



